"""Content processing tools."""

from typing import Any

from odin_backend.permissions.models import PermissionClass
from odin_backend.tools.base import Tool, ToolContext, ToolResult


def _simple_summarize(text: str, max_sentences: int = 5) -> str:
    sentences = [s.strip() for s in text.replace("\n", " ").split(".") if s.strip()]
    return ". ".join(sentences[:max_sentences]) + ("." if sentences else "")


class SummarizeContentTool(Tool):
    name = "summarize_content"
    description = "Summarize text content"
    permission_class = PermissionClass.SAFE

    async def execute(self, params: dict[str, Any], context: ToolContext) -> ToolResult:
        text = params.get("text", "")
        if not text and "contents" in params:
            parts = params["contents"]
            if isinstance(parts, list):
                text = "\n".join(
                    c.get("text", "") for c in parts if isinstance(c, dict)
                )
        if not text:
            return ToolResult(success=False, error="No text to summarize")

        summary = _simple_summarize(text, max_sentences=int(params.get("max_sentences", 8)))
        return ToolResult(
            success=True,
            data={"summary": summary, "source_length": len(text)},
        )


class GenerateEmailTool(Tool):
    name = "generate_email"
    description = "Generate email draft from content"
    permission_class = PermissionClass.SAFE

    async def execute(self, params: dict[str, Any], context: ToolContext) -> ToolResult:
        subject = params.get("subject", "ODIN Summary Report")
        body_source = params.get("text") or params.get("summary", "")
        if not body_source and "summary" in params.get("prior", {}):
            body_source = str(params["prior"]["summary"])

        body = f"""Hello,

Please find below the requested summary:

{body_source}

— Generated by PROJECT ODIN
"""
        return ToolResult(
            success=True,
            data={
                "subject": subject,
                "body": body,
                "to": params.get("to", ""),
            },
        )
