"""Dynamic execution contracts generated by the planner."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class RetryPolicy(BaseModel):
    max_retries: int = 3
    backoff_seconds: float = 2.0
    replan_on_exhaust: bool = True


class TimeoutPolicy(BaseModel):
    seconds: float = 120.0
    soft_timeout: float | None = None


class ValidationRule(BaseModel):
    kind: str = "exists"  # exists | schema | non_empty | custom
    target: str = ""
    json_schema: dict[str, Any] = Field(default_factory=dict, alias="schema")
    message: str = ""


class DependencySemantics(BaseModel):
    blocking: bool = True
    requires_output_from: list[str] = Field(default_factory=list)
    optional: bool = False


class DynamicExecutionContract(BaseModel):
    type: str = "execution"  # execution | validation | noop | deferred
    capability: str = "python.safe"
    tool: str | None = None
    params: dict[str, Any] = Field(default_factory=dict)
    expected_output: str | None = None
    validation: list[ValidationRule] = Field(default_factory=list)
    confidence: float = 0.75
    retry: RetryPolicy = Field(default_factory=RetryPolicy)
    timeout: TimeoutPolicy = Field(default_factory=TimeoutPolicy)
    dependency_semantics: DependencySemantics = Field(default_factory=DependencySemantics)
    parallelizable: bool = False
    blocking: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)

    def to_task_output(self) -> dict[str, Any]:
        out = {
            "type": self.type,
            "capability": self.capability,
            "params": self.params,
            "confidence": self.confidence,
            "parallelizable": self.parallelizable,
            "blocking": self.blocking,
            "expected_output": self.expected_output,
            "validation": [v.model_dump() for v in self.validation],
            "retry": self.retry.model_dump(),
            "timeout": self.timeout.model_dump(),
            "dependency_semantics": self.dependency_semantics.model_dump(),
        }
        if self.tool:
            out["tool"] = self.tool
        out.update(self.metadata)
        return out

    @classmethod
    def from_task_output(cls, output: dict[str, Any]) -> DynamicExecutionContract:
        retry_raw = output.get("retry") or {}
        timeout_raw = output.get("timeout") or {}
        dep_raw = output.get("dependency_semantics") or {}
        val_rules = [
            ValidationRule(**v) if isinstance(v, dict) else ValidationRule(kind=str(v))
            for v in (output.get("validation") or [])
        ]
        return cls(
            type=output.get("type", "execution"),
            capability=output.get("capability", "python.safe"),
            tool=output.get("tool"),
            params=output.get("params") or {},
            expected_output=output.get("expected_output"),
            validation=val_rules,
            confidence=float(output.get("confidence", 0.75)),
            retry=RetryPolicy(**retry_raw) if retry_raw else RetryPolicy(),
            timeout=TimeoutPolicy(**timeout_raw) if timeout_raw else TimeoutPolicy(),
            dependency_semantics=DependencySemantics(**dep_raw) if dep_raw else DependencySemantics(
                blocking=output.get("blocking", True),
                optional=not output.get("blocking", True),
            ),
            parallelizable=bool(output.get("parallelizable", False)),
            blocking=bool(output.get("blocking", True)),
            metadata={k: v for k, v in output.items() if k not in cls.model_fields},
        )


def contract_for_step(
    *,
    goal: str,
    capability: str,
    tool: str | None,
    params: dict[str, Any],
    confidence: float,
    expected_output: str | None = None,
    blocking: bool = True,
    parallelizable: bool = False,
    validation: list[ValidationRule] | None = None,
) -> DynamicExecutionContract:
    return DynamicExecutionContract(
        capability=capability,
        tool=tool,
        params=params,
        confidence=confidence,
        expected_output=expected_output,
        blocking=blocking,
        parallelizable=parallelizable,
        validation=validation or [],
    )
